### ISSUE TITLE
Chat app doesn't work with `user_ldap`

### ISSUE THREAD

**Issue by frykillr** [owncloud/chat#128]
Hi, i get this error in Explorer 11 and FireFox : An exception occurred while executing 'INSERT INTO `oc_chat_och_users_online`(`session_id`,`last_online`) VALUES(?,?)' with params ["48cd5aaa1ed881a4ee052e4593239919", 1409147193]: SQLSTATE[HY000]: General error: 1364 Field 'user' doesn't have a default value.

is it normal?

**Comment by juronius** [comment]
Hello,
Yes, i activated LDAP Backend.

**Comment by LEDfan** [comment]
Fixed in core, needs to be merged in 8.0.1.

**Comment by LEDfan** [comment]
@apg1980 @lunarok and others with LDAP problems please post a note in the PR at core, that you need this fix: https://github.com/owncloud/core/pull/13819

**Comment by LEDfan** [comment]
I managed to fix the Chat app instead of the core. It should work now with user_ldap. Try this [build.zip](http://downloadchat-ledfan.rhcloud.com/build.zip)

**Comment by apg1980** [comment]
after enabling your build.zip the owncloud stucks in a white screen, i have to disable the chat app in phpmyadmin.

**Comment by LEDfan** [comment]
@apg1980 I'm sorry, there was a dependency problem on the build server. I fixed it now.  [build.zip](http://downloadchat-ledfan.rhcloud.com/build.zip) Try again please.

**Comment by apg1980** [comment]
After enabling the new build.zip (thank u by the way), i've got the old error after opening the app:
Interner Serverfehler

DFatal 	index 	Exception: {"Message":"An exception occurred while executing '\t\t\tSELECT\n\t\t\t\t`user`\n\t\t\tFROM\n\t\t\t\t`oc_chat_och_users_online`':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_owncloud.oc_chat_och_users_online' doesn't exist","Code":0,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), '\\t\\t\\tSELECT\\n\\t\\t\\t\\t`...', Array)\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/db\/statementwrapper.php(65): Doctrine\\DBAL\\Statement->execute()\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/public\/appframework\/db\/mapper.php(213): OC_DB_StatementWrapper->execute()\n#4 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/db\/useronlinemapper.php(26): OCP\\AppFramework\\Db\\Mapper->execute('\\t\\t\\tSELECT\\n\\t\\t\\t\\t`...')\n#5 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/app\/chat.php(371): OCA\\Chat\\OCH\\Db\\UserOnlineMapper->getOnlineUsers()\n#6 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/app\/chat.php(520): OCA\\Chat\\App\\Chat->getContacts()\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/app\/chat.php(511): OCA\\Chat\\App\\Chat->getUserasContact('08598A5C-6FB6-4...')\n#8 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/controller\/appcontroller.php(65): OCA\\Chat\\App\\Chat->getCurrentUser()\n#9 [internal function]: OCA\\Chat\\Controller\\AppController->index()\n#10 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#11 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Chat\\Controller\\AppController), 'index')\n#12 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Chat\\Controller\\AppController), 'index')\n#13 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('AppController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/chat\/')\n#17 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(36): OC::handleRequest()\n#18 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":53}

**Comment by LEDfan** [comment]
Did you removed some tables from the Chat app maybe? Try to disable the Chat app via owncloud. Next execute the following queries: https://github.com/owncloud/chat/wiki/FAQ#uninstall-chat-app .(via e.g. PHPMyAdmin) next enable the Chat app again.  Thanks for your patient !

**Comment by apg1980** [comment]
after removing all entrys from der db table it works, but only after disabling the xmpp option in admin panel.
