### ISSUE TITLE
[404] Contact not found message shown in build version from 31.12.2014

### ISSUE THREAD

**Issue by j-ed** [owncloud/chat#190]
I wanted to test the current chat app build (build.zip from 31.12.2014) after I hadn't much luck with earlier
versions. Due to the fact that I wanted to start from a clean environment I followed the the recommendation and dropped all previous tables first before I enabled the chat app again.
```
DROP TABLE chat_och_conversations;
DROP TABLE chat_och_messages;
DROP TABLE chat_och_push_messages;
DROP TABLE chat_och_users_in_conversation;
DROP TABLE chat_och_users_online;
DROP TABLE chat_och_init_convs;
DELETE FROM appconfig WHERE `appid` = 'chat';
```
Unfortunately the following messages were shown once I try to access the app:
```
[404] Kontakt nicht gefunden
#0 /var/www/htdocs/owncloud/apps/contacts/lib/addressbookprovider.php(117): OCA\Contacts\Addressbook->getChild('1033')
#1 /var/www/htdocs/owncloud/lib/private/contactsmanager.php(40): OCA\Contacts\AddressbookProvider->search('', Array, Array)
#2 /var/www/htdocs/owncloud/apps2/chat/app/chat.php(270): OC\ContactsManager->search('', Array)
#3 /var/www/htdocs/owncloud/apps2/chat/controller/appcontroller.php(52): OCA\Chat\App\Chat->getContacts()
#4 [internal function]: OCA\Chat\Controller\AppController->index()
#5 /var/www/htdocs/owncloud/lib/private/appframework/http/dispatcher.php(155): call_user_func_array(Array, Array)
#6 /var/www/htdocs/owncloud/lib/private/appframework/http/dispatcher.php(84): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Chat\Controller\AppController), 'index')
#7 /var/www/htdocs/owncloud/lib/private/appframework/app.php(57): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Chat\Controller\AppController), 'index')
#8 /var/www/htdocs/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('AppController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#10 /var/www/htdocs/owncloud/lib/private/route/router.php(227): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#11 /var/www/htdocs/owncloud/lib/base.php(706): OC\Route\Router->match('/apps/chat/')
#12 /var/www/htdocs/owncloud/index.php(28): OC::handleRequest()
#13 {main}
```
I want to mention that by default all additional apps are installed in `./apps2` on my server so that the message `#11 `... OC\Route\Router->match('/apps/chat/') shows a wrong path information. Nevertheless I've also tried to move the app to the `./apps` directory but the error message keeps the same.

#### Server Configuration
OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 7.0.4

#### Client Configuration
Operating system: Windows 7
Browser: Mozilla Firefox v34.0

**Comment by LEDfan** [comment]
Hi. This is a bug in the Contacts app. This should be fixed in the latest contacts version.
