### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by wgreipl** [owncloud/chat#205]
after install i run the Chat.

this is the error

-------------
Exception: {"Message":"An exception occurred while executing '\t\t\tINSERT\n\t\t\tINTO `oc_chat_och_users_in_conversation`\n\t\t\t(\n\t\t\t\t`user`,\n\t\t\t\t`conversation_id`,\n\t\t\t\t`joined`\n\t\t\t) VALUES (\n\t\t\t\t?,\n\t\t\t\t?,\n\t\t\t\t?\n\t\t\t)' with params [null, \"CONV_ID_1424514520_53\", 1424514520]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user' cannot be null","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), '\\t\\t\\tINSSSSERT\\n\\t\\t\\t\\t\\t\\t\\t\\tArray)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(65): Doctrine\\DBAL\\Statement->execute()\n#3 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(213): OC_DB_StatementWrapper->execute()\n#4 \/var\/www\/owncloud\/apps\/chat\/lib\/och\/db\/usermapper.php(124): OCP\\AppFramework\\Db\\Mapper->execute('\\t\\t\\tINSSSSERT\\n\\t\\t\\t\\t\\t\\t\\t\\tArray)\n#5 \/var\/www\/owncloud\/apps\/chat\/lib\/och\/commands\/join.php(40): OCA\\Chat\\OCH\\Db\\UserMapper->insertUnique(Object(OCA\\Chat\\OCH\\Db\\User))\n#6 \/var\/www\/owncloud\/apps\/chat\/lib\/och\/commands\/startconv.php(69): OCA\\Chat\\OCH\\Commands\\Join->execute()\n#7 \/var\/www\/owncloud\/apps\/chat\/lib\/och\/och.php(75): OCA\\Chat\\OCH\\Commands\\StartConv->execute()\n#8

**Comment by LEDfan** [comment]
Are you using `user_ldap` as user backend in core?

**Comment by wgreipl** [comment]
yes!

have the Chat a Problem with user_ldap
