### ISSUE TITLE
Chat app crashes ownCloud when Contacts not activated?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/chat#210]
When enabling the Chat app, I get this error:

```
PHP Fatal error:  Call to a member function getContacts() on a non-object
in owncloud/apps/chat/lib/xmpp/xmpp.php on line 16,
referer: http://localhorst/owncloud/index.php/settings/apps
```

And then my ownCloud is whitescreened. Is that cause I don’t have the Contacts app enabled at the moment? Since Chat works with the internal users as well, Contacts should not be a hard requirement.

@LEDfan :)

**Comment by LEDfan** [comment]
Contacts app isn't a dependency :) (Luckily!)
There was something wrong with the DI injection. Fixed in https://github.com/owncloud/chat/commit/8e60237ab8e1692c002e4d08a08c6afbf3298304 .

**Comment by jancborchardt** [comment]
Ok – still getting this here though:
```
{"reqId":"IxyoHUXoDVpPe2qUhG01","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 2 passed to OCA\\Chat\\XMPP\\XMPP::__construct() must be an instance of OCA\\Chat\\XMPP\\IConfig, instance of OC\\AllConfig given, called in \/home\/jan\/owncloud-dev\/apps\/chat\/app\/chat.php on line 331 and defined at \/home\/jan\/owncloud-dev\/apps\/chat\/lib\/xmpp\/xmpp.php#14","level":3,"time":"2015-02-26T13:21:15+00:00"}
{"reqId":"HhCmobKYx8cjxWhyyNBJ","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/integrated.min serverroot:\\\/home\\\/jan\\\/owncloud-dev\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/templatelayout.php(188): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/templatelayout.php(139): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/template.php(127): OC_TemplateLayout->__construct('user', 'files')\\n#3 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/template\\\/base.php(120): OC_Template->fetchPage()\\n#4 \\\/home\\\/jan\\\/owncloud-dev\\\/apps\\\/files\\\/index.php(156): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/route\\\/route.php(151) : runtime-created function(1): require_once('\\\/home\\\/jan\\\/owncl...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/route\\\/router.php(270): call_user_func('?lambda_1', Array)\\n#8 \\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/base.php(824): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#9 \\\/home\\\/jan\\\/owncloud-dev\\\/index.php(38): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud-dev\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":61}","level":4,"time":"2015-02-26T13:21:15+00:00"}
{"reqId":"N7oIFM9bWeq3BD0A1M0n","remoteAddr":"127.0.0.1","app":"PHP","message":"js file not found: script:js\/integrated.min serverroot:\/home\/jan\/owncloud-dev at \/home\/jan\/owncloud-dev\/lib\/private\/template\/resourcelocator.php#61","level":3,"time":"2015-02-26T13:21:15+00:00"}
```

**Comment by LEDfan** [comment]
@jancborchardt I'm fixing the first error. However the Chat app isn't working because the JS code isn't minified. You have two options:
 - install Grunt and run the `grunt` command (https://github.com/owncloud/chat#important-run-grunt-when-you-change-js-files)
 - download the packaged owncloud app (http://downloadchat-ledfan.rhcloud.com/build.zip)

**Comment by jancborchardt** [comment]
Great, got it now using
```
sudo npm install
grunt
```
Didn’t check the readme first. ;) Is it possible to instead of whitescreening showing that note as an error?

**Comment by LEDfan** [comment]
Glad it is solved! I have created an issue about the error reporting here #212. There is also a first implementation.

**Comment by jancborchardt** [comment]
Nice! :)
