### ISSUE TITLE
SQL exception spamming log with postgres and chat 0.4.0

### ISSUE THREAD

**Issue by jperville** [owncloud/chat#217]
I have installed chat 0.4.0 (downloaded from the github release page).
Using postgresql (9.3.6) from Ubuntu 14.04 LTS 64 bits as database.
PHP version is 5.5.9.

I can use the application (after disabling user_ldap) but I see the following messages spam in my owncloud log:

```json
{
  "Line": 91,
  "File": "/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php",
  "Trace": "
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE \"chat_oc...', Array)\n
#2 /var/www/owncloud/lib/private/db/statementwrapper.php(65): Doctrine\\DBAL\\Statement->execute()\n
#3 /var/www/owncloud/lib/public/appframework/db/mapper.php(213): OC_DB_StatementWrapper->execute()\n
#4 /var/www/owncloud/apps2/chat/lib/och/db/useronlinemapper.php(59): OCP\\AppFramework\\Db\\Mapper->execute('UPDATE `*PREFIX...', Array)\n
#5 /var/www/owncloud/apps2/chat/lib/och/commands/online.php(22): OCA\\Chat\\OCH\\Db\\UserOnlineMapper->updateLastOnline('75e02f86d649695...', 1428238754.584)\n
#6 /var/www/owncloud/apps2/chat/controller/och/apicontroller.php(69): OCA\\Chat\\OCH\\Commands\\Online->execute()\n
#7 [internal function]: OCA\\Chat\\Controller\\OCH\\ApiController->route('command::online...', Array)\n
#8 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)\n
#9 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Chat\\Controller\\OCH\\ApiController), 'route')\n
#10 /var/www/owncloud/lib/private/appframework/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Chat\\Controller\\OCH\\ApiController), 'route')\n
#11 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\\AppFramework\\App::main('ApiController', 'route', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#12 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n
#13 /var/www/owncloud/lib/private/route/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n
#14 /var/www/owncloud/lib/base.php(767): OC\\Route\\Router->match('/apps/chat/och/...')\n
#15 /var/www/owncloud/index.php(36): OC::handleRequest()\n#16 {main}",
  "Code": 0,
  "Message": "An exception occurred while executing 'UPDATE \"chat_och_users_online\" SET \"last_online\" = ? WHERE \"session_id\" = ?' with params [1428238754.584, \"75e02f86d64969527cb24acc00e7c485\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: \"1428238754.584\""
}
```

Here is how the `chat_och_users_online` table looks like in postgres:

```sh
Password for user owncloud: 
psql (9.3.6)
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
Type "help" for help.

owncloud=> \d chat_och_users_online
                                    Table "public.chat_och_users_online"
   Column    |          Type           |                             Modifiers                              
-------------+-------------------------+--------------------------------------------------------------------
 id          | integer                 | not null default nextval('chat_och_users_online_id_seq'::regclass)
 user        | character varying(64)   | not null
 session_id  | character varying(2000) | not null
 last_online | bigint                  | not null
Indexes:
    "chat_och_users_online_pkey" PRIMARY KEY, btree (id)

owncloud=> \q
```

As indicated by the postgres error message ("Invalid text representation: 7 ERROR: invalid input syntax for integer: \"1428238754.584\""), shouldn't the `last_online` column be a timestamp or fixed point decimal instead of large integer? Another possibility is to cast the timestamp into integer before persisting it in the database.

**Comment by jperville** [comment]
I replaced all instances of 'bigint' in `appinfo/database.yml` with 'numeric' (which is a valid column type for postgresql, mysql and sqlite3). It may be less efficient in terms of storage in the database but it is good enough for me workaround.

**Comment by LEDfan** [comment]
Thanks for testing the Chat app @jperville. Your work around should work, but the real cause is that it isn't a real timestamp.

ed4c0693009d75c382ba175a01990ac20afa5f59 should fix this issue. Can you check this?

**Comment by jperville** [comment]
Thanks @LEDfan! Your proposed fix is indeed better than my workaround of changing the columns in the database definition.

Since I am not using oc 8.1 yet I could not test directly from github master, but I was able to backport your simple patch to my chef cookbooks and verify that the problem is fixed.

**Comment by LEDfan** [comment]
Great! Thanks @jperville.
